# Generated by Django 6.0.3 on 2026-03-15 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dmm_id', models.BigIntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('ruby', models.CharField(blank=True, max_length=255, null=True)),
                ('image_path_small', models.CharField(blank=True, max_length=500, null=True)),
                ('image_path_lerge', models.CharField(blank=True, max_length=500, null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DmmGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ruby', models.CharField(blank=True, max_length=255, null=True)),
                ('list_url_dmm', models.CharField(blank=True, max_length=500, null=True)),
                ('is_exist_genre', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['sort_order'], name='adaken_cate_sort_or_1cbe4d_idx'), models.Index(fields=['is_active'], name='adaken_cate_is_acti_220ec3_idx')],
            },
        ),
        migrations.CreateModel(
            name='MajorGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dmm_id', models.BigIntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('ruby', models.CharField(blank=True, max_length=255, null=True)),
                ('list_url_dmm', models.CharField(blank=True, max_length=500, null=True)),
                ('is_must_medium', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='major_genres', to='adaken.category')),
            ],
        ),
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dmm_id', models.BigIntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('ruby', models.CharField(max_length=255, null=True)),
                ('list_url_dmm', models.CharField(max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['is_active'], name='adaken_make_is_acti_ffa172_idx')],
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dmm_id', models.BigIntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('ruby', models.CharField(max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('maker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Maker', to='adaken.maker')),
            ],
        ),
        migrations.CreateModel(
            name='MediumGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dmm_id', models.BigIntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('ruby', models.CharField(blank=True, max_length=255, null=True)),
                ('list_url_dmm', models.CharField(blank=True, max_length=500, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('major_genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medium_genres', to='adaken.majorgenre')),
            ],
        ),
        migrations.CreateModel(
            name='Actress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dmm_id', models.BigIntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('ruby', models.CharField(blank=True, max_length=255, null=True)),
                ('other_name', models.CharField(blank=True, max_length=255, null=True)),
                ('image_path_small', models.CharField(blank=True, max_length=500, null=True)),
                ('image_path_lerge', models.CharField(blank=True, max_length=500, null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('birth', models.DateField(blank=True, null=True)),
                ('bust', models.FloatField(blank=True, null=True)),
                ('cup', models.CharField(blank=True, max_length=100, null=True)),
                ('waist', models.FloatField(blank=True, null=True)),
                ('hip', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('blood_type', models.CharField(blank=True, max_length=20, null=True)),
                ('hobby', models.CharField(blank=True, max_length=255, null=True)),
                ('prefectures', models.CharField(blank=True, max_length=100, null=True)),
                ('debut_year', models.DateField(blank=True, null=True)),
                ('digital_url', models.CharField(blank=True, max_length=500, null=True)),
                ('monthly_url', models.CharField(blank=True, max_length=500, null=True)),
                ('mono_url', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actresses', to='adaken.office')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dmm_id', models.BigIntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('ruby', models.CharField(blank=True, max_length=255, null=True)),
                ('list_url_dmm', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series', to='adaken.label')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dmm_id', models.BigIntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('affiliate_url', models.CharField(max_length=500, null=True)),
                ('product_number', models.CharField(max_length=64)),
                ('sale_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='adaken.label')),
                ('maker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='adaken.maker')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='adaken.series')),
            ],
        ),
        migrations.CreateModel(
            name='VoteWorkGenreDelete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('complete_flg', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('major_genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_delete_vote_relations', to='adaken.majorgenre')),
                ('medium_genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_delete_vote_relations', to='adaken.mediumgenre')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre_delete_vote_relations', to='adaken.work')),
            ],
        ),
        migrations.CreateModel(
            name='VoteWorkGenreAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('complete_flg', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('major_genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_add_vote_relations', to='adaken.majorgenre')),
                ('medium_genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_add_vote_relations', to='adaken.mediumgenre')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre_add_vote_relations', to='adaken.work')),
            ],
        ),
        migrations.CreateModel(
            name='VoteWorkActress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('complete_flg', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_work_actress_actress_relations', to='adaken.actress')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_work_actress_work_relations', to='adaken.work')),
            ],
        ),
        migrations.CreateModel(
            name='WorkActress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_main', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_relations', to='adaken.actress')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actress_relations', to='adaken.work')),
            ],
        ),
        migrations.CreateModel(
            name='WorkActressDirector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_actress_director_actress_relations', to='adaken.actress')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_actress_director_director_relations', to='adaken.director')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_actress_director_work_relations', to='adaken.work')),
            ],
        ),
        migrations.CreateModel(
            name='WorkGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_by', models.CharField(default='admin', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('major_genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_relations', to='adaken.majorgenre')),
                ('medium_genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_relations', to='adaken.mediumgenre')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre_relations', to='adaken.work')),
            ],
        ),
        migrations.CreateModel(
            name='WorkImage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sort', models.IntegerField(default=1)),
                ('url', models.CharField(max_length=1024)),
                ('type', models.IntegerField(choices=[(1, 'imageURL'), (2, 'sampleImageURL')])),
                ('size_type', models.IntegerField(choices=[(1, 'list'), (2, 'small'), (3, 'large'), (4, 'sample_s'), (5, 'sample_l')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work', models.ForeignKey(db_column='work_id', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='adaken.work')),
            ],
        ),
        migrations.CreateModel(
            name='WorkSampleMovie',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=1024)),
                ('size_type', models.IntegerField(choices=[(1, 'size_476_306'), (2, 'size_560_360'), (3, 'size_644_414'), (4, 'size_720_480')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work', models.ForeignKey(db_column='work_id', on_delete=django.db.models.deletion.CASCADE, related_name='sample_movies', to='adaken.work')),
            ],
        ),
        migrations.AddIndex(
            model_name='majorgenre',
            index=models.Index(fields=['category', 'sort_order'], name='adaken_majo_categor_d27ac7_idx'),
        ),
        migrations.AddIndex(
            model_name='majorgenre',
            index=models.Index(fields=['is_active'], name='adaken_majo_is_acti_7f7463_idx'),
        ),
        migrations.AddConstraint(
            model_name='majorgenre',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='uniq_major_genre_category_name'),
        ),
        migrations.AddIndex(
            model_name='mediumgenre',
            index=models.Index(fields=['major_genre', 'sort_order'], name='adaken_medi_major_g_9f8e4c_idx'),
        ),
        migrations.AddIndex(
            model_name='mediumgenre',
            index=models.Index(fields=['is_active'], name='adaken_medi_is_acti_5197cd_idx'),
        ),
        migrations.AddConstraint(
            model_name='mediumgenre',
            constraint=models.UniqueConstraint(fields=('major_genre', 'name'), name='uniq_medium_genre_major_name'),
        ),
        migrations.AddIndex(
            model_name='actress',
            index=models.Index(fields=['name'], name='adaken_actr_name_59ee65_idx'),
        ),
        migrations.AddIndex(
            model_name='actress',
            index=models.Index(fields=['cup'], name='adaken_actr_cup_8b59bd_idx'),
        ),
        migrations.AddIndex(
            model_name='actress',
            index=models.Index(fields=['hip'], name='adaken_actr_hip_fb0493_idx'),
        ),
        migrations.AddIndex(
            model_name='actress',
            index=models.Index(fields=['height'], name='adaken_actr_height_2d8e93_idx'),
        ),
        migrations.AddIndex(
            model_name='series',
            index=models.Index(fields=['name'], name='adaken_seri_name_ccba88_idx'),
        ),
        migrations.AddIndex(
            model_name='series',
            index=models.Index(fields=['is_active'], name='adaken_seri_is_acti_56aece_idx'),
        ),
        migrations.AddIndex(
            model_name='series',
            index=models.Index(fields=['label'], name='adaken_seri_label_i_5e52c0_idx'),
        ),
        migrations.AddIndex(
            model_name='work',
            index=models.Index(fields=['product_number'], name='adaken_work_product_0abc8f_idx'),
        ),
        migrations.AddIndex(
            model_name='work',
            index=models.Index(fields=['sale_date'], name='adaken_work_sale_da_068585_idx'),
        ),
        migrations.AddIndex(
            model_name='work',
            index=models.Index(fields=['maker', 'product_number'], name='adaken_work_maker_i_6425d0_idx'),
        ),
        migrations.AddIndex(
            model_name='work',
            index=models.Index(fields=['is_active'], name='adaken_work_is_acti_ce5e8a_idx'),
        ),
        migrations.AddIndex(
            model_name='voteworkgenredelete',
            index=models.Index(fields=['complete_flg', 'count'], name='adaken_vote_complet_13dfff_idx'),
        ),
        migrations.AddIndex(
            model_name='voteworkgenredelete',
            index=models.Index(fields=['work'], name='adaken_vote_work_id_61b70f_idx'),
        ),
        migrations.AddIndex(
            model_name='voteworkgenredelete',
            index=models.Index(fields=['major_genre'], name='adaken_vote_major_g_4ae140_idx'),
        ),
        migrations.AddIndex(
            model_name='voteworkgenredelete',
            index=models.Index(fields=['medium_genre'], name='adaken_vote_medium__9df0c2_idx'),
        ),
        migrations.AddConstraint(
            model_name='voteworkgenredelete',
            constraint=models.UniqueConstraint(condition=models.Q(('medium_genre__isnull', True)), fields=('work', 'major_genre'), name='uniq_delvote_work_major_when_medium_null'),
        ),
        migrations.AddConstraint(
            model_name='voteworkgenredelete',
            constraint=models.UniqueConstraint(condition=models.Q(('medium_genre__isnull', False)), fields=('work', 'medium_genre'), name='uniq_delvote_work_medium_when_medium_not_null'),
        ),
        migrations.AddIndex(
            model_name='voteworkgenreadd',
            index=models.Index(fields=['complete_flg', 'count'], name='adaken_vote_complet_7b4d57_idx'),
        ),
        migrations.AddIndex(
            model_name='voteworkgenreadd',
            index=models.Index(fields=['work'], name='adaken_vote_work_id_492f1b_idx'),
        ),
        migrations.AddIndex(
            model_name='voteworkgenreadd',
            index=models.Index(fields=['major_genre'], name='adaken_vote_major_g_71cd68_idx'),
        ),
        migrations.AddIndex(
            model_name='voteworkgenreadd',
            index=models.Index(fields=['medium_genre'], name='adaken_vote_medium__89813a_idx'),
        ),
        migrations.AddConstraint(
            model_name='voteworkgenreadd',
            constraint=models.UniqueConstraint(condition=models.Q(('medium_genre__isnull', True)), fields=('work', 'major_genre'), name='uniq_addvote_work_major_when_medium_null'),
        ),
        migrations.AddConstraint(
            model_name='voteworkgenreadd',
            constraint=models.UniqueConstraint(condition=models.Q(('medium_genre__isnull', False)), fields=('work', 'medium_genre'), name='uniq_addvote_work_medium_when_medium_not_null'),
        ),
        migrations.AddIndex(
            model_name='voteworkactress',
            index=models.Index(fields=['work'], name='adaken_vote_work_id_a6bac3_idx'),
        ),
        migrations.AddIndex(
            model_name='voteworkactress',
            index=models.Index(fields=['actress'], name='adaken_vote_actress_b82f3c_idx'),
        ),
        migrations.AddConstraint(
            model_name='voteworkactress',
            constraint=models.UniqueConstraint(fields=('work', 'actress'), name='uniq_work_actress_director'),
        ),
        migrations.AddIndex(
            model_name='workactress',
            index=models.Index(fields=['work', 'sort_order'], name='adaken_work_work_id_b4f665_idx'),
        ),
        migrations.AddIndex(
            model_name='workactress',
            index=models.Index(fields=['actress'], name='adaken_work_actress_ffac7b_idx'),
        ),
        migrations.AddIndex(
            model_name='workactress',
            index=models.Index(fields=['is_main'], name='adaken_work_is_main_e56710_idx'),
        ),
        migrations.AddConstraint(
            model_name='workactress',
            constraint=models.UniqueConstraint(fields=('work', 'actress'), name='uniqu_work_actress'),
        ),
        migrations.AddIndex(
            model_name='workactressdirector',
            index=models.Index(fields=['work'], name='adaken_work_work_id_242b2b_idx'),
        ),
        migrations.AddIndex(
            model_name='workactressdirector',
            index=models.Index(fields=['actress'], name='adaken_work_actress_edd091_idx'),
        ),
        migrations.AddIndex(
            model_name='workactressdirector',
            index=models.Index(fields=['director'], name='adaken_work_directo_f6699c_idx'),
        ),
        migrations.AddConstraint(
            model_name='workactressdirector',
            constraint=models.UniqueConstraint(fields=('work', 'actress', 'director'), name='work_actress_director_uniq_work_actress_director'),
        ),
        migrations.AddIndex(
            model_name='workgenre',
            index=models.Index(fields=['major_genre', 'work'], name='adaken_work_major_g_56a649_idx'),
        ),
        migrations.AddIndex(
            model_name='workgenre',
            index=models.Index(fields=['medium_genre', 'work'], name='adaken_work_medium__841c9d_idx'),
        ),
        migrations.AddIndex(
            model_name='workgenre',
            index=models.Index(fields=['work'], name='adaken_work_work_id_5b7917_idx'),
        ),
        migrations.AddConstraint(
            model_name='workgenre',
            constraint=models.UniqueConstraint(condition=models.Q(('medium_genre__isnull', True)), fields=('work', 'major_genre'), name='uniq_workgenre_major_row'),
        ),
        migrations.AddConstraint(
            model_name='workgenre',
            constraint=models.UniqueConstraint(condition=models.Q(('medium_genre__isnull', False)), fields=('work', 'medium_genre'), name='uniq_workgenre_medium_row'),
        ),
        migrations.AddIndex(
            model_name='workimage',
            index=models.Index(fields=['work', 'type', 'size_type', 'sort'], name='adaken_work_work_id_dd328d_idx'),
        ),
        migrations.AddConstraint(
            model_name='workimage',
            constraint=models.UniqueConstraint(fields=('work', 'type', 'size_type', 'sort'), name='uniq_work_image_type_size_sort'),
        ),
        migrations.AddIndex(
            model_name='worksamplemovie',
            index=models.Index(fields=['work', 'size_type'], name='adaken_work_work_id_3bcf17_idx'),
        ),
        migrations.AddConstraint(
            model_name='worksamplemovie',
            constraint=models.UniqueConstraint(fields=('work', 'size_type'), name='uniq_work_sample_movie_size'),
        ),
    ]
