# Generated by Django 6.0.3 on 2026-03-15 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaken', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='director_work', to='adaken.director'),
        ),
        migrations.AlterField(
            model_name='work',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='work',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='label_work', to='adaken.label'),
        ),
        migrations.AlterField(
            model_name='work',
            name='maker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maker_work', to='adaken.maker'),
        ),
        migrations.AlterField(
            model_name='work',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series_work', to='adaken.series'),
        ),
    ]
