# Generated by Django 6.0.3 on 2026-03-15 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaken', '0002_work_director_alter_work_is_active_alter_work_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='site_type',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
