# Generated by Django 6.0.3 on 2026-03-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaken', '0003_work_site_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workimage',
            name='uniq_work_image_type_size_sort',
        ),
        migrations.RemoveIndex(
            model_name='workimage',
            name='adaken_work_work_id_dd328d_idx',
        ),
        migrations.AlterField(
            model_name='work',
            name='sale_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='workimage',
            index=models.Index(fields=['work', 'type', 'size_type'], name='adaken_work_work_id_fb604f_idx'),
        ),
        migrations.AddConstraint(
            model_name='workimage',
            constraint=models.UniqueConstraint(fields=('work', 'type', 'size_type'), name='uniq_work_image_type_size_sort'),
        ),
    ]
