# Generated by Django 6.0.3 on 2026-03-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaken', '0004_remove_workimage_uniq_work_image_type_size_sort_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workimage',
            name='uniq_work_image_type_size_sort',
        ),
        migrations.AddConstraint(
            model_name='workimage',
            constraint=models.UniqueConstraint(fields=('work', 'type', 'size_type', 'sort'), name='uniq_work_image_type_size_sort'),
        ),
    ]
