# Generated by Django 6.0.3 on 2026-03-16 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaken', '0005_remove_workimage_uniq_work_image_type_size_sort_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoreMajorGenreDmm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dmm_id', models.BigIntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('major_genres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='major_genres', to='adaken.majorgenre')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('major_genres', 'dmm_id'), name='uniq_more_major_genre_dmm_id')],
            },
        ),
        migrations.CreateModel(
            name='MoreMediumGenreDmm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dmm_id', models.BigIntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('medium_genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medium_genre', to='adaken.mediumgenre')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('medium_genre', 'dmm_id'), name='uniq_more_medium_genre_dmm_id')],
            },
        ),
    ]
