from __future__ import annotations

from django.core.management.base import BaseCommand
from django.db import transaction

from adaken.models import MajorGenre, MediumGenre


MEDIUM_SEEDS = [
    # =========================
    # 衣装 > 制服
    # =========================
    (
        MediumGenre.COSTUME_SEIFUKU_SAILOR,
        MajorGenre.COSTUME_SEIFUKU,
        "セーラー服",
        "せーらーふく",
        10,
    ),
    (
        MediumGenre.COSTUME_SEIFUKU_BLAZER,
        MajorGenre.COSTUME_SEIFUKU,
        "ブレザー",
        "ぶれざー",
        20,
    ),
    # =========================
    # 衣装 > コスプレ
    # =========================
    (
        MediumGenre.COSTUME_COSPLAY_NURSE,
        MajorGenre.COSTUME_COSPLAY,
        "ナース",
        "なーす",
        10,
    ),
    (
        MediumGenre.COSTUME_COSPLAY_MAID,
        MajorGenre.COSTUME_COSPLAY,
        "メイド",
        "めいど",
        20,
    ),
    (
        MediumGenre.COSTUME_COSPLAY_CHINA,
        MajorGenre.COSTUME_COSPLAY,
        "チャイナドレス",
        "ちゃいなどれす",
        30,
    ),
    (
        MediumGenre.COSTUME_COSPLAY_BONDAGE,
        MajorGenre.COSTUME_COSPLAY,
        "ボンテージ",
        "ぼんてーじ",
        40,
    ),
    (
        MediumGenre.COSTUME_COSPLAY_BODYCON,
        MajorGenre.COSTUME_COSPLAY,
        "ボディコン",
        "ぼでぃこん",
        50,
    ),
    (
        MediumGenre.COSTUME_COSPLAY_MINISKIRT_POLICE,
        MajorGenre.COSTUME_COSPLAY,
        "ミニスカポリス",
        "みにすかぽりす",
        60,
    ),
    (
        MediumGenre.COSTUME_COSPLAY_BUNNY,
        MajorGenre.COSTUME_COSPLAY,
        "バニーガール",
        "ばにーがーる",
        70,
    ),
    (
        MediumGenre.COSTUME_COSPLAY_SUIT_OL,
        MajorGenre.COSTUME_COSPLAY,
        "スーツ/OL",
        "すーつ おーえる",
        80,
    ),
    (
        MediumGenre.COSTUME_COSPLAY_CHEER,
        MajorGenre.COSTUME_COSPLAY,
        "チアガール",
        "ちあがーる",
        90,
    ),
    (
        MediumGenre.COSTUME_COSPLAY_CAT,
        MajorGenre.COSTUME_COSPLAY,
        "ネコミミ・獣系",
        "ねこみみけものけい",
        100,
    ),
    (
        MediumGenre.COSTUME_COSPLAY_NAKED_APRON,
        MajorGenre.COSTUME_COSPLAY,
        "裸エプロン",
        "はだかえぷろん",
        110,
    ),
    # =========================
    # 衣装 > 露出状態
    # =========================
    (
        MediumGenre.COSTUME_EXPOSURE_ALL,
        MajorGenre.COSTUME_EXPOSURE,
        "全着",
        "ぜんちゃく",
        10,
    ),
    (
        MediumGenre.COSTUME_EXPOSURE_HALF,
        MajorGenre.COSTUME_EXPOSURE,
        "半ぬぎ",
        "はんぬぎ",
        20,
    ),
    (
        MediumGenre.COSTUME_EXPOSURE_OPEN,
        MajorGenre.COSTUME_EXPOSURE,
        "はだけ",
        "はだけ",
        30,
    ),
    (
        MediumGenre.COSTUME_EXPOSURE_SEE_THROUGH,
        MajorGenre.COSTUME_EXPOSURE,
        "透け",
        "すけ",
        40,
    ),
    # =========================
    # 衣装 > 水着
    # =========================
    (
        MediumGenre.COSTUME_SWIM_NORMAL,
        MajorGenre.COSTUME_SWIMSUIT,
        "ノーマル水着",
        "のーまるみずぎ",
        10,
    ),
    (
        MediumGenre.COSTUME_SWIM_BIKINI,
        MajorGenre.COSTUME_SWIMSUIT,
        "ビキニ",
        "びきに",
        20,
    ),
    (
        MediumGenre.COSTUME_SWIM_SCHOOL,
        MajorGenre.COSTUME_SWIMSUIT,
        "競泳・スクール水着",
        "きょうえいすくーるみずぎ",
        30,
    ),
    # =========================
    # 衣装 > 下着
    # =========================
    (
        MediumGenre.COSTUME_UNDER_BRA,
        MajorGenre.COSTUME_UNDERWEAR,
        "ブラ・ショーツ",
        "ぶら しょーつ",
        10,
    ),
    (
        MediumGenre.COSTUME_UNDER_TBACK,
        MajorGenre.COSTUME_UNDERWEAR,
        "Tバック",
        "てぃーばっく",
        20,
    ),
    (
        MediumGenre.COSTUME_UNDER_LINGERIE,
        MajorGenre.COSTUME_UNDERWEAR,
        "ランジェリー",
        "らんじぇりー",
        30,
    ),
    (
        MediumGenre.COSTUME_UNDER_GARTER,
        MajorGenre.COSTUME_UNDERWEAR,
        "ガーターベルト",
        "がーたーべると",
        40,
    ),
    (
        MediumGenre.COSTUME_UNDER_SPORTS,
        MajorGenre.COSTUME_UNDERWEAR,
        "スポブラ",
        "すぽぶら",
        50,
    ),
    (
        MediumGenre.COSTUME_UNDER_NO_BRA,
        MajorGenre.COSTUME_UNDERWEAR,
        "ノーブラ",
        "のーぶら",
        60,
    ),
    (
        MediumGenre.COSTUME_UNDER_NO_PANTIES,
        MajorGenre.COSTUME_UNDERWEAR,
        "ノーパン",
        "のーぱん",
        70,
    ),
    (
        MediumGenre.COSTUME_UNDER_PANTY_FLASH,
        MajorGenre.COSTUME_UNDERWEAR,
        "パンチラ",
        "ぱんちら",
        80,
    ),
    # =========================
    # 衣装 > パンスト
    # =========================
    (
        MediumGenre.COSTUME_PANTY_TIGHTS,
        MajorGenre.COSTUME_PANTYHOSE,
        "タイツ",
        "たいつ",
        10,
    ),
    (
        MediumGenre.COSTUME_PANTY_STOCKING,
        MajorGenre.COSTUME_PANTYHOSE,
        "ストッキング",
        "すとっきんぐ",
        20,
    ),
    (
        MediumGenre.COSTUME_PANTY_KNEE,
        MajorGenre.COSTUME_PANTYHOSE,
        "ニーハイ",
        "にーはい",
        30,
    ),
    (
        MediumGenre.COSTUME_PANTY_LOOSE,
        MajorGenre.COSTUME_PANTYHOSE,
        "ルーズソックス",
        "るーずそっくす",
        40,
    ),
    (
        MediumGenre.COSTUME_PANTY_KNEE_SOX,
        MajorGenre.COSTUME_PANTYHOSE,
        "ニーソックス",
        "にーそっくす",
        50,
    ),
    # =========================
    # 衣装 > 和服・浴衣
    # =========================
    (
        MediumGenre.COSTUME_WAFUKU_YUKATA,
        MajorGenre.COSTUME_WAFUKU,
        "浴衣",
        "ゆかた",
        10,
    ),
    (
        MediumGenre.COSTUME_WAFUKU_KIMONO,
        MajorGenre.COSTUME_WAFUKU,
        "着物",
        "きもの",
        20,
    ),
    (
        MediumGenre.COSTUME_WAFUKU_COS,
        MajorGenre.COSTUME_WAFUKU,
        "和風コス",
        "わふうこす",
        30,
    ),
    # =========================
    # 衣装 > スポーツ
    # =========================
    (
        MediumGenre.COSTUME_SPORT_GYM,
        MajorGenre.COSTUME_SPORTS,
        "体操着・ブルマ",
        "たいそうぎ ぶるま",
        10,
    ),
    (
        MediumGenre.COSTUME_SPORT_VOLLEY,
        MajorGenre.COSTUME_SPORTS,
        "バレー",
        "ばれー",
        20,
    ),
    (
        MediumGenre.COSTUME_SPORT_TENNIS,
        MajorGenre.COSTUME_SPORTS,
        "テニス",
        "てにす",
        30,
    ),
    (
        MediumGenre.COSTUME_SPORT_BICYCLE,
        MajorGenre.COSTUME_SPORTS,
        "自転車",
        "じてんしゃ",
        40,
    ),
    # =========================
    # 場所
    # =========================
    (MediumGenre.PLACE_HOME_BED, MajorGenre.PLACE_HOME, "ベッド", "べっど", 10),
    (MediumGenre.PLACE_HOME_LIVING, MajorGenre.PLACE_HOME, "リビング", "りびんぐ", 20),
    (MediumGenre.PLACE_HOME_BATH, MajorGenre.PLACE_HOME, "お風呂", "おふろ", 30),
    (MediumGenre.PLACE_HOME_KITCHEN, MajorGenre.PLACE_HOME, "キッチン", "きっちん", 40),
    (MediumGenre.PLACE_SCHOOL_CLASS, MajorGenre.PLACE_SCHOOL, "教室", "きょうしつ", 10),
    (
        MediumGenre.PLACE_SCHOOL_GYM,
        MajorGenre.PLACE_SCHOOL,
        "体育館",
        "たいいくかん",
        20,
    ),
    (
        MediumGenre.PLACE_SCHOOL_POOL,
        MajorGenre.PLACE_SCHOOL,
        "プール/更衣室",
        "ぷーる こういしつ",
        30,
    ),
    (
        MediumGenre.PLACE_HOTEL_LUXURY,
        MajorGenre.PLACE_HOTEL,
        "ラグジュアリー",
        "らぐじゅありー",
        10,
    ),
    (
        MediumGenre.PLACE_HOTEL_LOVE,
        MajorGenre.PLACE_HOTEL,
        "ラブホテル",
        "らぶほてる",
        20,
    ),
    (
        MediumGenre.PLACE_POOL_SCHOOL,
        MajorGenre.PLACE_POOL,
        "学校のプール",
        "がっこうのぷーる",
        10,
    ),
    (
        MediumGenre.PLACE_POOL_NIGHT,
        MajorGenre.PLACE_POOL,
        "ナイトプール",
        "ないとぷーる",
        20,
    ),
    (
        MediumGenre.PLACE_POOL_PRIVATE,
        MajorGenre.PLACE_POOL,
        "プライベートプール",
        "ぷらいべーとぷーる",
        30,
    ),
    # =========================
    # シチュエーション > 関係性
    # =========================
    (
        MediumGenre.SITUATION_RELATION_COUPLE,
        MajorGenre.SITUATION_RELATION,
        "カップル",
        "かっぷる",
        10,
    ),
    (
        MediumGenre.SITUATION_RELATION_MARRIED,
        MajorGenre.SITUATION_RELATION,
        "夫婦",
        "ふうふ",
        20,
    ),
    (
        MediumGenre.SITUATION_RELATION_COLLEAGUE,
        MajorGenre.SITUATION_RELATION,
        "同僚",
        "どうりょう",
        30,
    ),
    (
        MediumGenre.SITUATION_RELATION_CLASSMATE,
        MajorGenre.SITUATION_RELATION,
        "同級生",
        "どうきゅうせい",
        40,
    ),
    (
        MediumGenre.SITUATION_RELATION_AFFAIR,
        MajorGenre.SITUATION_RELATION,
        "不倫",
        "ふりん",
        50,
    ),
    (
        MediumGenre.SITUATION_RELATION_NTR,
        MajorGenre.SITUATION_RELATION,
        "NTR",
        "えぬてぃーあーる",
        60,
    ),
    (
        MediumGenre.SITUATION_RELATION_FEMALE_BOSS,
        MajorGenre.SITUATION_RELATION,
        "女上司",
        "おんなじょうし",
        70,
    ),
    (
        MediumGenre.SITUATION_RELATION_MALE_BOSS,
        MajorGenre.SITUATION_RELATION,
        "男上司",
        "おとこじょうし",
        80,
    ),
    (
        MediumGenre.SITUATION_RELATION_BRIDE,
        MajorGenre.SITUATION_RELATION,
        "花嫁",
        "はなよめ",
        90,
    ),
    (
        MediumGenre.SITUATION_RELATION_CHILDHOOD,
        MajorGenre.SITUATION_RELATION,
        "幼なじみ",
        "おさななじみ",
        100,
    ),
    (
        MediumGenre.SITUATION_RELATION_DAUGHTER,
        MajorGenre.SITUATION_RELATION,
        "娘・養女",
        "むすめ ようじょ",
        110,
    ),
    (
        MediumGenre.SITUATION_RELATION_CLUB_MANAGER,
        MajorGenre.SITUATION_RELATION,
        "部活・マネージャー",
        "ぶかつ まねーじゃー",
        120,
    ),
    (
        MediumGenre.SITUATION_RELATION_SUBORDINATE,
        MajorGenre.SITUATION_RELATION,
        "部下・同僚",
        "ぶか どうりょう",
        130,
    ),
    (
        MediumGenre.SITUATION_RELATION_INCEST,
        MajorGenre.SITUATION_RELATION,
        "近親相姦",
        "きんしんそうかん",
        140,
    ),
    (
        MediumGenre.SITUATION_RELATION_IN_LAW,
        MajorGenre.SITUATION_RELATION,
        "義母",
        "ぎぼ",
        140,
    ),
    # =========================
    # シチュエーション > シーン
    # =========================
    (
        MediumGenre.SITUATION_SCENE_WORK,
        MajorGenre.SITUATION_SCENE,
        "仕事中",
        "しごとちゅう",
        10,
    ),
    (
        MediumGenre.SITUATION_SCENE_DATE,
        MajorGenre.SITUATION_SCENE,
        "デート",
        "でーと",
        20,
    ),
    (
        MediumGenre.SITUATION_SCENE_NANPA,
        MajorGenre.SITUATION_SCENE,
        "ナンパ",
        "なんぱ",
        30,
    ),
    (
        MediumGenre.SITUATION_SCENE_GYAKUNAN,
        MajorGenre.SITUATION_SCENE,
        "逆ナン",
        "ぎゃくなん",
        40,
    ),
    (
        MediumGenre.SITUATION_SCENE_GOUKON,
        MajorGenre.SITUATION_SCENE,
        "飲み会・合コン",
        "のみかい ごうこん",
        50,
    ),
    (
        MediumGenre.SITUATION_SCENE_PRIVATE,
        MajorGenre.SITUATION_SCENE,
        "プライベート",
        "ぷらいべーと",
        60,
    ),
    (
        MediumGenre.SITUATION_SCENE_AMATEUR,
        MajorGenre.SITUATION_SCENE,
        "素人",
        "しろうと",
        70,
    ),
    (
        MediumGenre.SITUATION_SCENE_TRAVEL,
        MajorGenre.SITUATION_SCENE,
        "旅行",
        "りょこう",
        80,
    ),
    (
        MediumGenre.SITUATION_SCENE_MASSAGE,
        MajorGenre.SITUATION_SCENE,
        "マッサージ・リフレ",
        "まっさーじ りふれ",
        90,
    ),
    (
        MediumGenre.SITUATION_SCENE_PEEPING,
        MajorGenre.SITUATION_SCENE,
        "盗撮・のぞき",
        "とうさつ のぞき",
        100,
    ),
    # =========================
    # シチュエーション > 風俗
    # =========================
    (
        MediumGenre.SITUATION_FUZOKU_MENESU,
        MajorGenre.SITUATION_FUZOKU,
        "メンエス",
        "めんえす",
        10,
    ),
    (
        MediumGenre.SITUATION_FUZOKU_PINSARO,
        MajorGenre.SITUATION_FUZOKU,
        "ピンサロ",
        "ぴんさろ",
        20,
    ),
    (
        MediumGenre.SITUATION_FUZOKU_CABARET,
        MajorGenre.SITUATION_FUZOKU,
        "キャバクラ",
        "きゃばくら",
        30,
    ),
    (
        MediumGenre.SITUATION_FUZOKU_SEX_CABARET,
        MajorGenre.SITUATION_FUZOKU,
        "セクキャバ",
        "せくきゃば",
        40,
    ),
    (
        MediumGenre.SITUATION_FUZOKU_GIRLSBAR,
        MajorGenre.SITUATION_FUZOKU,
        "ガールズバー",
        "がーるずばー",
        50,
    ),
    (
        MediumGenre.SITUATION_FUZOKU_HEALTH_SOAP,
        MajorGenre.SITUATION_FUZOKU,
        "ヘルス・ソープ",
        "へるす そーぷ",
        60,
    ),
    # =========================
    # シチュエーション > 職業
    # =========================
    (
        MediumGenre.SITUATION_JOB_WIFE,
        MajorGenre.SITUATION_JOB,
        "人妻・主婦",
        "ひとづま しゅふ",
        10,
    ),
    (
        MediumGenre.SITUATION_JOB_HOUSEWIFE,
        MajorGenre.SITUATION_JOB,
        "主婦",
        "しゅふ",
        20,
    ),
    (
        MediumGenre.SITUATION_JOB_SECRETARY,
        MajorGenre.SITUATION_JOB,
        "秘書",
        "ひしょ",
        30,
    ),
    (
        MediumGenre.SITUATION_JOB_BEAUTICIAN,
        MajorGenre.SITUATION_JOB,
        "美容師",
        "びようし",
        40,
    ),
    (
        MediumGenre.SITUATION_JOB_TEACHER,
        MajorGenre.SITUATION_JOB,
        "女教師",
        "おんなきょうし",
        50,
    ),
    (
        MediumGenre.SITUATION_JOB_TUTOR,
        MajorGenre.SITUATION_JOB,
        "家庭教師",
        "かていきょうし",
        60,
    ),
    (
        MediumGenre.SITUATION_JOB_ATHLETE,
        MajorGenre.SITUATION_JOB,
        "アスリート",
        "あすりーと",
        70,
    ),
    (
        MediumGenre.SITUATION_JOB_RECEPTIONIST,
        MajorGenre.SITUATION_JOB,
        "受付嬢",
        "うけつけじょう",
        80,
    ),
    (
        MediumGenre.SITUATION_JOB_INVESTIGATOR,
        MajorGenre.SITUATION_JOB,
        "女捜査官",
        "おんなそうさかん",
        90,
    ),
    (
        MediumGenre.SITUATION_JOB_CABARET_GIRL,
        MajorGenre.SITUATION_JOB,
        "キャバ嬢・風俗嬢",
        "きゃばじょう ふうぞくじょう",
        100,
    ),
    (
        MediumGenre.SITUATION_JOB_COLLEGE_GIRL,
        MajorGenre.SITUATION_JOB,
        "女子大生",
        "じょしだいせい",
        110,
    ),
    (
        MediumGenre.SITUATION_JOB_SCHOOL_GIRL,
        MajorGenre.SITUATION_JOB,
        "女子校生",
        "じょしこうせい",
        120,
    ),
    (
        MediumGenre.SITUATION_JOB_MATURE_WOMAN,
        MajorGenre.SITUATION_JOB,
        "熟女",
        "じゅくじょ",
        130,
    ),
    (
        MediumGenre.SITUATION_JOB_NURSE,
        MajorGenre.SITUATION_JOB,
        "看護婦・ナース",
        "かんごふ なーす",
        140,
    ),
    (
        MediumGenre.SITUATION_JOB_BUS_GUIDE,
        MajorGenre.SITUATION_JOB,
        "バスガイド",
        "ばすがいど",
        150,
    ),
    (
        MediumGenre.SITUATION_JOB_RACE_QUEEN,
        MajorGenre.SITUATION_JOB,
        "レースクィーン",
        "れーすくいーん",
        160,
    ),
    (
        MediumGenre.SITUATION_JOB_MODEL,
        MajorGenre.SITUATION_JOB,
        "モデル",
        "もでる",
        170,
    ),
    (
        MediumGenre.SITUATION_JOB_INSTRUCTOR,
        MajorGenre.SITUATION_JOB,
        "インストラクター",
        "いんすとらくたー",
        180,
    ),
    (MediumGenre.SITUATION_JOB_OL, MajorGenre.SITUATION_JOB, "OL", "おーえる", 190),
    (
        MediumGenre.SITUATION_JOB_GEINOU,
        MajorGenre.SITUATION_JOB,
        "アイドル・芸能人",
        "あいどるげいのうじん",
        190,
    ),
    (MediumGenre.SITUATION_JOB_MIKO, MajorGenre.SITUATION_JOB, "巫女", "みこ", 190),
    (
        MediumGenre.SITUATION_JOB_PRINCE,
        MajorGenre.SITUATION_JOB,
        "お姫様",
        "おひめさま",
        190,
    ),
    (
        MediumGenre.SITUATION_JOB_OKAMI,
        MajorGenre.SITUATION_JOB,
        "女将・女主人",
        "おかみおんなしゅじん",
        190,
    ),
    (
        MediumGenre.SITUATION_JOB_CANGAL,
        MajorGenre.SITUATION_JOB,
        "キャンギャル",
        "きゃんぎゃる",
        190,
    ),
    (
        MediumGenre.SITUATION_JOB_CA,
        MajorGenre.SITUATION_JOB,
        "スチュワーデス",
        "すちゅわーです",
        190,
    ),
    (MediumGenre.SITUATION_JOB_JOI, MajorGenre.SITUATION_JOB, "女医", "じょい", 190),
    (
        MediumGenre.SITUATION_JOB_ANNOUNCER,
        MajorGenre.SITUATION_JOB,
        "女子アナ",
        "じょしあな",
        190,
    ),
    (
        MediumGenre.SITUATION_JOB_MIBOUJIN,
        MajorGenre.SITUATION_JOB,
        "未亡人",
        "みぼうじん",
        190,
    ),
    (
        MediumGenre.SITUATION_JOB_WAITRESS,
        MajorGenre.SITUATION_JOB,
        "ウェイトレス",
        "うぇいとれす",
        190,
    ),
    (
        MediumGenre.SITUATION_JOB_COMPANION,
        MajorGenre.SITUATION_JOB,
        "コンパニオン",
        "こんぱにおん",
        190,
    ),
    (
        MediumGenre.SITUATION_JOB_GOKUDO,
        MajorGenre.SITUATION_JOB,
        "極道・任侠",
        "ごくどうにんきょう",
        190,
    ),
    (
        MediumGenre.SITUATION_JOB_KUNOICHI,
        MajorGenre.SITUATION_JOB,
        "くノ一",
        "くのいち",
        190,
    ),
    # =========================
    # シチュエーション > 寝取り・寝取られ・NTR
    # =========================
    (MediumGenre.SITUATION_NTR_TAKER, MajorGenre.SITUATION_NTR, "寝取り", "ねとり", 10),
    (
        MediumGenre.SITUATION_NTR_TAKEN,
        MajorGenre.SITUATION_NTR,
        "寝取られ",
        "ねとられ",
        20,
    ),
    # =========================
    # 女優
    # =========================
    (
        MediumGenre.PERSON_STYLE_SLENDER,
        MajorGenre.PERSON_STYLE,
        "スレンダー",
        "すれんだー",
        10,
    ),
    (
        MediumGenre.PERSON_STYLE_GLAMOUR,
        MajorGenre.PERSON_STYLE,
        "グラマー",
        "ぐらまー",
        20,
    ),
    (MediumGenre.PERSON_STYLE_SMALL, MajorGenre.PERSON_STYLE, "小柄", "こがら", 30),
    (MediumGenre.PERSON_STYLE_TALL, MajorGenre.PERSON_STYLE, "長身", "ちょうしん", 40),
    (MediumGenre.PERSON_STYLE_CURVY, MajorGenre.PERSON_STYLE, "くびれ", "くびれ", 50),
    (
        MediumGenre.PERSON_STYLE_HAIRLESS,
        MajorGenre.PERSON_STYLE,
        "パイパン",
        "ぱいぱん",
        60,
    ),
    (MediumGenre.PERSON_STYLE_TANNED, MajorGenre.PERSON_STYLE, "日焼け", "ひやけ", 70),
    (
        MediumGenre.PERSON_STYLE_NO_MAKEUP,
        MajorGenre.PERSON_STYLE,
        "すっぴん",
        "すっぴん",
        80,
    ),
    (MediumGenre.PERSON_BREAST_BIG, MajorGenre.PERSON_BREAST, "巨乳", "きょにゅう", 10),
    (
        MediumGenre.PERSON_BREAST_BEAUTIFUL,
        MajorGenre.PERSON_BREAST,
        "美乳",
        "びにゅう",
        20,
    ),
    (
        MediumGenre.PERSON_BREAST_SMALL,
        MajorGenre.PERSON_BREAST,
        "貧乳・微乳",
        "ひんにゅう びにゅう",
        30,
    ),
    (MediumGenre.PERSON_HIP_BEAUTIFUL, MajorGenre.PERSON_HIP, "美尻", "びじり", 10),
    (MediumGenre.PERSON_HIP_BIG, MajorGenre.PERSON_HIP, "巨尻", "きょじり", 20),
    (MediumGenre.PERSON_LEG_BEAUTIFUL, MajorGenre.PERSON_LEG, "美脚", "びきゃく", 10),
    (
        MediumGenre.PERSON_TYPE_BISHOUJO,
        MajorGenre.PERSON_TYPE,
        "美少女",
        "びしょうじょ",
        10,
    ),
    (MediumGenre.PERSON_TYPE_SEISO, MajorGenre.PERSON_TYPE, "清楚", "せいそ", 20),
    (MediumGenre.PERSON_TYPE_GAL, MajorGenre.PERSON_TYPE, "ギャル", "ぎゃる", 30),
    (
        MediumGenre.PERSON_TYPE_COOL,
        MajorGenre.PERSON_TYPE,
        "クール・綺麗",
        "くーる きれい",
        40,
    ),
    (MediumGenre.PERSON_TYPE_CUTE, MajorGenre.PERSON_TYPE, "可愛い", "かわいい", 50),
    (
        MediumGenre.PERSON_TYPE_BOYISH,
        MajorGenre.PERSON_TYPE,
        "ボーイッシュ",
        "ぼーいっしゅ",
        60,
    ),
    (MediumGenre.PERSON_TYPE_M, MajorGenre.PERSON_TYPE, "M女", "えむおんな", 70),
    (MediumGenre.PERSON_TYPE_GLASSES, MajorGenre.PERSON_TYPE, "めがね", "めがね", 80),
    (
        MediumGenre.PERSON_TYPE_ONEESAN,
        MajorGenre.PERSON_TYPE,
        "お姉さん",
        "おねえさん",
        90,
    ),
    (MediumGenre.PERSON_TYPE_VIRGIN, MajorGenre.PERSON_TYPE, "処女", "しょじょ", 90),
    (MediumGenre.PERSON_TYPE_BITCH, MajorGenre.PERSON_TYPE, "ビッチ", "びっち", 100),
    (
        MediumGenre.PERSON_PERSONALITY_COOL,
        MajorGenre.PERSON_PERSONALITY,
        "クール",
        "くーる",
        10,
    ),
    (
        MediumGenre.PERSON_PERSONALITY_TSUNDERE,
        MajorGenre.PERSON_PERSONALITY,
        "ツンデレ",
        "つんでれ",
        20,
    ),
    (
        MediumGenre.PERSON_PERSONALITY_BRAT,
        MajorGenre.PERSON_PERSONALITY,
        "生意気",
        "なまいき",
        30,
    ),
    (
        MediumGenre.PERSON_PERSONALITY_CHIJO,
        MajorGenre.PERSON_PERSONALITY,
        "痴女",
        "ちじょ",
        40,
    ),
    (
        MediumGenre.PERSON_HAIR_VERY_LONG,
        MajorGenre.PERSON_HAIR_STYLE,
        "ベリーロング",
        "べりーろんぐ",
        10,
    ),
    (
        MediumGenre.PERSON_HAIR_LONG,
        MajorGenre.PERSON_HAIR_STYLE,
        "ロング",
        "ろんぐ",
        20,
    ),
    (
        MediumGenre.PERSON_HAIR_SHORT,
        MajorGenre.PERSON_HAIR_STYLE,
        "ショート",
        "しょーと",
        30,
    ),
    (
        MediumGenre.PERSON_HAIR_VERY_SHORT,
        MajorGenre.PERSON_HAIR_STYLE,
        "ベリーショート",
        "べりーしょーと",
        40,
    ),
    (MediumGenre.PERSON_HAIR_BOB, MajorGenre.PERSON_HAIR_STYLE, "ボブ", "ぼぶ", 50),
    (
        MediumGenre.PERSON_HAIR_PONYTAIL,
        MajorGenre.PERSON_HAIR_STYLE,
        "ポニーテール",
        "ぽにーてーる",
        60,
    ),
    (
        MediumGenre.PERSON_HAIR_TWINTAIL,
        MajorGenre.PERSON_HAIR_STYLE,
        "ツインテール",
        "ついんてーる",
        70,
    ),
    (
        MediumGenre.PERSON_HAIR_COLOR_BLACK,
        MajorGenre.PERSON_HAIR_COLOR,
        "黒髪",
        "くろかみ",
        10,
    ),
    (
        MediumGenre.PERSON_HAIR_COLOR_BLONDE,
        MajorGenre.PERSON_HAIR_COLOR,
        "金髪",
        "きんぱつ",
        20,
    ),
    (
        MediumGenre.PERSON_HAIR_COLOR_BROWN,
        MajorGenre.PERSON_HAIR_COLOR,
        "茶髪",
        "ちゃぱつ",
        30,
    ),
    (MediumGenre.PERSON_VOICE_CUTE, MajorGenre.PERSON_VOICE, "可愛い", "かわいい", 10),
    (MediumGenre.PERSON_VOICE_OHO, MajorGenre.PERSON_VOICE, "オホ声", "おほごえ", 20),
    # =========================
    # 男優
    # =========================
    (
        MediumGenre.PERSON_M_STYLE_MUSCLE,
        MajorGenre.PERSON_M_STYLE,
        "筋肉質",
        "きんにくしつ",
        10,
    ),
    (
        MediumGenre.PERSON_M_STYLE_CHUBBY,
        MajorGenre.PERSON_M_STYLE,
        "ぽっちゃり",
        "ぽっちゃり",
        20,
    ),
    (
        MediumGenre.PERSON_M_STYLE_THIN,
        MajorGenre.PERSON_M_STYLE,
        "ガリガリ",
        "がりがり",
        30,
    ),
    (
        MediumGenre.PERSON_M_STYLE_BIG_D,
        MajorGenre.PERSON_M_STYLE,
        "デカチン・巨根",
        "でかちん きょこん",
        40,
    ),
    (
        MediumGenre.PERSON_M_TYPE_IKEMEN,
        MajorGenre.PERSON_M_TYPE,
        "イケメン",
        "いけめん",
        10,
    ),
    (
        MediumGenre.PERSON_M_TYPE_VIRGIN,
        MajorGenre.PERSON_M_TYPE,
        "童貞",
        "どうてい",
        20,
    ),
    (
        MediumGenre.PERSON_M_TYPE_GAY,
        MajorGenre.PERSON_M_TYPE,
        "ゲイ",
        "げい",
        30,
    ),
    (
        MediumGenre.PERSON_M_TYPE_PE,
        MajorGenre.PERSON_M_TYPE,
        "早漏",
        "そうろう",
        40,
    ),
    (
        MediumGenre.PERSON_M_TYPE_M,
        MajorGenre.PERSON_M_TYPE,
        "M男",
        "えむお",
        50,
    ),
    # =========================
    # プレイ
    # =========================
    (MediumGenre.PLAY_BACK_SLEEP, MajorGenre.PLAY_BACK, "寝バック", "ねばっく", 10),
    (MediumGenre.PLAY_BACK_STAND, MajorGenre.PLAY_BACK, "立ちバック", "たちばっく", 20),
    (MediumGenre.PLAY_BACK_DOGGY, MajorGenre.PLAY_BACK, "四つん這い", "よつんばい", 30),
    (
        MediumGenre.PLAY_FELLATIO_IMA,
        MajorGenre.PLAY_FELLATIO,
        "イラマチオ",
        "いらまちお",
        10,
    ),
    (
        MediumGenre.PLAY_FELLATIO_JUPO,
        MajorGenre.PLAY_FELLATIO,
        "じゅぽふぇら",
        "じゅぽふぇら",
        20,
    ),
    (
        MediumGenre.PLAY_FELLATIO_PERO,
        MajorGenre.PLAY_FELLATIO,
        "ぺろぺろフェラ",
        "ぺろぺろふぇら",
        30,
    ),
    (
        MediumGenre.PLAY_FELLATIO_INSTANT,
        MajorGenre.PLAY_FELLATIO,
        "即しゃく",
        "そくしゃく",
        40,
    ),
    (MediumGenre.PLAY_HANDJOB_NORMAL, MajorGenre.PLAY_HANDJOB, "手コキ", "てこき", 10),
    (MediumGenre.PLAY_HANDJOB_FOOT, MajorGenre.PLAY_HANDJOB, "足コキ", "あしこき", 20),
    (
        MediumGenre.PLAY_HANDJOB_TOY,
        MajorGenre.PLAY_HANDJOB,
        "オナホコキ",
        "おなほこき",
        30,
    ),
    (MediumGenre.PLAY_HANDJOB_ARM, MajorGenre.PLAY_HANDJOB, "脇コキ", "わきこき", 40),
    (
        MediumGenre.PLAY_HANDJOB_THIGH,
        MajorGenre.PLAY_HANDJOB,
        "太ももコキ",
        "ふとももこき",
        50,
    ),
    (
        MediumGenre.PLAY_HANDJOB_PAIZURI,
        MajorGenre.PLAY_HANDJOB,
        "パイズリ",
        "ぱいずり",
        60,
    ),
    (MediumGenre.PLAY_SQUIRT_MASSIVE, MajorGenre.PLAY_SQUIRT, "大量", "たいりょう", 10),
    (
        MediumGenre.PLAY_SQUIRT_MALE,
        MajorGenre.PLAY_SQUIRT,
        "男の潮吹き",
        "おとこのしおふき",
        20,
    ),
    (
        MediumGenre.PLAY_LOTION_MASSAGE,
        MajorGenre.PLAY_LOTION,
        "マッサージ",
        "まっさーじ",
        10,
    ),
    (
        MediumGenre.PLAY_MULTI_3P_4P,
        MajorGenre.PLAY_MULTI,
        "3P・4P",
        "すりーぴー よんぴー",
        10,
    ),
    (MediumGenre.PLAY_MULTI_RANKOU, MajorGenre.PLAY_MULTI, "乱交", "らんこう", 20),
    (MediumGenre.PLAY_MULTI_HARLEM, MajorGenre.PLAY_MULTI, "ハーレム", "はーれむ", 30),
    (MediumGenre.PLAY_MULTI_F1_3P, MajorGenre.PLAY_MULTI_F1, "3P", "すりーぴー", 10),
    (MediumGenre.PLAY_MULTI_F1_4P, MajorGenre.PLAY_MULTI_F1, "4P", "ふぉーぴー", 20),
    (
        MediumGenre.PLAY_MULTI_F1_5P,
        MajorGenre.PLAY_MULTI_F1,
        "5P以上",
        "ごぴーいじょう",
        30,
    ),
    (MediumGenre.PLAY_MULTI_M1_3P, MajorGenre.PLAY_MULTI_M1, "3P", "すりーぴー", 10),
    (MediumGenre.PLAY_MULTI_M1_4P, MajorGenre.PLAY_MULTI_M1, "4P", "ふぉーぴー", 20),
    (
        MediumGenre.PLAY_MULTI_M1_5P,
        MajorGenre.PLAY_MULTI_M1,
        "5P以上",
        "ごぴーいじょう",
        30,
    ),
    (MediumGenre.PLAY_MULTI_MM_2_2, MajorGenre.PLAY_MULTI_MULTI, "2:2", "にたいに", 10),
    (
        MediumGenre.PLAY_MULTI_MM_3_3,
        MajorGenre.PLAY_MULTI_MULTI,
        "3:3",
        "さんたいさん",
        20,
    ),
    (
        MediumGenre.PLAY_MULTI_MM_4_4,
        MajorGenre.PLAY_MULTI_MULTI,
        "4:4",
        "よんたいよん",
        30,
    ),
    (MediumGenre.PLAY_MULTI_MM_5_5, MajorGenre.PLAY_MULTI_MULTI, "5:5", "ごたいご", 40),
    (
        MediumGenre.PLAY_FINISH_NAKADASHI,
        MajorGenre.PLAY_FINISH,
        "中出し",
        "なかだし",
        10,
    ),
    (
        MediumGenre.PLAY_FINISH_GOMU,
        MajorGenre.PLAY_FINISH,
        "ゴム中出し",
        "ごむなかだし",
        20,
    ),
    (MediumGenre.PLAY_FINISH_FACIAL, MajorGenre.PLAY_FINISH, "顔射", "がんしゃ", 30),
    (
        MediumGenre.PLAY_FINISH_BOOBS,
        MajorGenre.PLAY_FINISH,
        "おっぱい発射",
        "おっぱいはっしゃ",
        40,
    ),
    (
        MediumGenre.PLAY_FINISH_ASS,
        MajorGenre.PLAY_FINISH,
        "お尻発射",
        "おしりはっしゃ",
        50,
    ),
    (
        MediumGenre.PLAY_FINISH_GOKKUN,
        MajorGenre.PLAY_FINISH,
        "ごっくん",
        "ごっくん",
        60,
    ),
    (
        MediumGenre.PLAY_FINISH_BUKKAKE,
        MajorGenre.PLAY_FINISH,
        "ぶっかけ",
        "ぶっかけ",
        70,
    ),
    (MediumGenre.PLAY_DRUG_PILL, MajorGenre.PLAY_DRUG, "薬", "くすり", 10),
    (
        MediumGenre.PLAY_DRUG_LOTION,
        MajorGenre.PLAY_DRUG,
        "ローション",
        "ろーしょん",
        20,
    ),
    (MediumGenre.PLAY_DRUG_TABACCO, MajorGenre.PLAY_DRUG, "タバコ", "たばこ", 30),
    (
        MediumGenre.PLAY_FOREPLAY_69,
        MajorGenre.PLAY_FOREPLAY,
        "69",
        "ろくじゅうきゅう",
        10,
    ),
    (MediumGenre.PLAY_FOREPLAY_CUNNI, MajorGenre.PLAY_FOREPLAY, "クンニ", "くんに", 20),
    (
        MediumGenre.PLAY_FOREPLAY_FACE_SIT,
        MajorGenre.PLAY_FOREPLAY,
        "顔面騎乗",
        "がんめんきじょう",
        30,
    ),
    (
        MediumGenre.PLAY_FOREPLAY_SIX_NINE,
        MajorGenre.PLAY_FOREPLAY,
        "シックスナイン",
        "しっくすないん",
        40,
    ),
    (MediumGenre.PLAY_HARD_PISTON, MajorGenre.PLAY_HARD, "ピストン", "ぴすとん", 10),
    (
        MediumGenre.PLAY_HARD_ORGASM,
        MajorGenre.PLAY_HARD,
        "アクメ・オーガズム",
        "あくめ おーがずむ",
        20,
    ),
    (
        MediumGenre.PLAY_HARD_WHITE_EYES,
        MajorGenre.PLAY_HARD,
        "白目・失神",
        "しろめ しっしん",
        30,
    ),
    (
        MediumGenre.PLAY_HARD_SPANKING,
        MajorGenre.PLAY_HARD,
        "スパンキング",
        "すぱんきんぐ",
        40,
    ),
    (
        MediumGenre.PLAY_HARD_ANAL,
        MajorGenre.PLAY_HARD,
        "アナルセックス",
        "あなるせっくす",
        50,
    ),
    (
        MediumGenre.PLAY_HARD_BONDAGE,
        MajorGenre.PLAY_HARD,
        "縛り・緊縛",
        "しばり きんばく",
        60,
    ),
    (MediumGenre.PLAY_HARD_ENEMA, MajorGenre.PLAY_HARD, "浣腸", "かんちょう", 70),
    (MediumGenre.PLAY_HARD_SCAT, MajorGenre.PLAY_HARD, "脱糞", "だっぷん", 80),
    (MediumGenre.PLAY_HARD_DRUG, MajorGenre.PLAY_HARD, "ドラッグ", "どらっぐ", 90),
    (MediumGenre.PLAY_HARD_CONFINEMENT, MajorGenre.PLAY_HARD, "監禁", "かんきん", 100),
    (MediumGenre.PLAY_HARD_SM, MajorGenre.PLAY_HARD, "SM", "えすえむ", 110),
    (MediumGenre.PLAY_HARD_PREGNANCY, MajorGenre.PLAY_HARD, "孕ませ", "はらませ", 120),
    (MediumGenre.PLAY_HARD_KOUSOKU, MajorGenre.PLAY_HARD, "拘束", "こうそく", 130),
    (MediumGenre.PLAY_HARD_HUMILIATION, MajorGenre.PLAY_HARD, "辱め", "はずかしめ", 90),
    (MediumGenre.PLAY_HARD_CRUEL, MajorGenre.PLAY_HARD, "鬼畜", "きちく", 100),
    (
        MediumGenre.PLAY_HARD_SCATOLOGY,
        MajorGenre.PLAY_HARD,
        "スカトロ",
        "すかとろあしふぇち",
        111,
    ),
    (MediumGenre.PLAY_HARD_ANAL, MajorGenre.PLAY_HARD, "アナル", "あなる", 112),
    (MediumGenre.PLAY_HARD_VERBAL_ABUSE, MajorGenre.PLAY_HARD, "罵倒", "ばとう", 113),
    (MediumGenre.PLAY_TOY_DILDO, MajorGenre.PLAY_TOY, "ディルド", "でぃるど", 10),
    (MediumGenre.PLAY_TOY_DENMA, MajorGenre.PLAY_TOY, "電マ", "でんま", 20),
    (MediumGenre.PLAY_TOY_ROTOR, MajorGenre.PLAY_TOY, "ローター", "ろーたー", 30),
    (MediumGenre.PLAY_TOY_VIBE, MajorGenre.PLAY_TOY, "バイブ", "ばいぶ", 40),
    (
        MediumGenre.PLAY_FETISH_SWAPPING,
        MajorGenre.PLAY_FETISH,
        "スワッピング・夫婦交換",
        "すわっぴんぐ ふうふこうかん",
        10,
    ),
    (MediumGenre.PLAY_FETISH_MILK, MajorGenre.PLAY_FETISH, "母乳", "ぼにゅう", 20),
    (MediumGenre.PLAY_FETISH_DIRTY_TALK, MajorGenre.PLAY_FETISH, "淫語", "いんご", 30),
    (
        MediumGenre.PLAY_FETISH_URINE_DRINK,
        MajorGenre.PLAY_FETISH,
        "飲尿",
        "いんにょう",
        40,
    ),
    (
        MediumGenre.PLAY_FETISH_URINATION,
        MajorGenre.PLAY_FETISH,
        "放尿・お漏らし",
        "ほうにょう おもらし",
        50,
    ),
    (MediumGenre.PLAY_FETISH_SHOTA, MajorGenre.PLAY_FETISH, "ショタ", "しょた", 60),
    (MediumGenre.PLAY_FETISH_ASS, MajorGenre.PLAY_FETISH, "尻フェチ", "しりふぇち", 70),
    (MediumGenre.PLAY_FETISH_LEG, MajorGenre.PLAY_FETISH, "脚フェチ", "あしふぇち", 80),
    (
        MediumGenre.PLAY_FETISH_FUTANARI,
        MajorGenre.PLAY_FETISH,
        "ふたなり",
        "ふたなり",
        90,
    ),
    (
        MediumGenre.PLAY_FETISH_TENTACLE_PLAY,
        MajorGenre.PLAY_FETISH,
        "触手",
        "しょくしゅ",
        100,
    ),
    (
        MediumGenre.PLAY_FETISH_BOYS_LOVE,
        MajorGenre.PLAY_FETISH,
        "BL（ボーイズラブ）",
        "ぼーいずらぶ",
        111,
    ),
    (
        MediumGenre.PLAY_FETISH_CROSSDRESSING,
        MajorGenre.PLAY_FETISH,
        "女装・男の娘",
        "じょそうおとこのこ",
        112,
    ),
    (
        MediumGenre.PLAY_FETISH_TRANS_WOMAN,
        MajorGenre.PLAY_FETISH,
        "ニューハーフ",
        "にゅーはーふ",
        113,
    ),
    (MediumGenre.PLAY_LES_SISTERS, MajorGenre.PLAY_LES, "姉・妹", "あね いもうと", 10),
]


class Command(BaseCommand):
    help = "Seed MediumGenre. Idempotent."

    @transaction.atomic
    def handle(self, *args, **options):
        self.stdout.write(self.style.NOTICE("Seeding medium genres..."))
        MediumGenre.objects.all().delete()
        for id, major_genre_id, name, ruby, sort_order in MEDIUM_SEEDS:
            MediumGenre.objects.update_or_create(
                id=id,
                defaults={
                    "major_genre_id": major_genre_id,
                    "name": name,
                    "ruby": ruby,
                    "sort_order": sort_order,
                    "is_active": True,
                },
            )

        self.stdout.write(self.style.SUCCESS("✅ seed_medium_genre completed."))
