from __future__ import annotations

from django.core.management.base import BaseCommand
from django.db import connection, transaction

from adaken.models import Category, MajorGenre, MediumGenre


MAJOR_SEEDS = [
    # (id, category_id, dmm_id, name, ruby, list_url_dmm, is_must_medium, sort_order)
    # =========================
    # 衣装
    # =========================
    (
        MajorGenre.COSTUME_SEIFUKU,
        Category.COSTUME,
        None,
        "学生服",
        "がくせいふく",
        "",
        True,
        10,
    ),
    (
        MajorGenre.COSTUME_COSPLAY,
        Category.COSTUME,
        None,
        "コスプレ",
        "こすぷれ",
        "",
        True,
        20,
    ),
    (
        MajorGenre.COSTUME_EXPOSURE,
        Category.COSTUME,
        None,
        "露出状態",
        "ろしゅつじょうたい",
        "",
        True,
        30,
    ),
    (
        MajorGenre.COSTUME_SWIMSUIT,
        Category.COSTUME,
        None,
        "水着",
        "みずぎ",
        "",
        True,
        40,
    ),
    (
        MajorGenre.COSTUME_UNDERWEAR,
        Category.COSTUME,
        None,
        "下着",
        "したぎ",
        "",
        True,
        50,
    ),
    (
        MajorGenre.COSTUME_PANTYHOSE,
        Category.COSTUME,
        None,
        "パンスト・タイツ",
        "ぱんすとたいつ",
        "",
        True,
        60,
    ),
    (
        MajorGenre.COSTUME_WAFUKU,
        Category.COSTUME,
        None,
        "和服・浴衣",
        "わふく ゆかた",
        "",
        True,
        70,
    ),
    (
        MajorGenre.COSTUME_SPORTS,
        Category.COSTUME,
        None,
        "スポーツ",
        "すぽーつ",
        "",
        True,
        80,
    ),
    (
        MajorGenre.COSTUME_MINISKIRT,
        Category.COSTUME,
        None,
        "ミニスカ",
        "みにすか",
        "",
        False,
        90,
    ),
    # =========================
    # 場所
    # =========================
    (MajorGenre.PLACE_HOME, Category.PLACE, None, "自宅", "じたく", "", True, 10),
    (MajorGenre.PLACE_SCHOOL, Category.PLACE, None, "学校", "がっこう", "", True, 20),
    (MajorGenre.PLACE_HOTEL, Category.PLACE, None, "ホテル", "ほてる", "", True, 30),
    (MajorGenre.PLACE_RYOKAN, Category.PLACE, None, "旅館", "りょかん", "", False, 40),
    (
        MajorGenre.PLACE_OFFICE,
        Category.PLACE,
        None,
        "オフィス",
        "おふぃす",
        "",
        False,
        50,
    ),
    (
        MajorGenre.PLACE_CAR_SEX,
        Category.PLACE,
        None,
        "カーセックス",
        "かーせっくす",
        "",
        False,
        60,
    ),
    (MajorGenre.PLACE_SEA, Category.PLACE, None, "海", "うみ", "", False, 70),
    (MajorGenre.PLACE_ONSEN, Category.PLACE, None, "温泉", "おんせん", "", False, 80),
    (
        MajorGenre.PLACE_HOSPITAL,
        Category.PLACE,
        None,
        "病院・クリニック",
        "びょういん くりにっく",
        "",
        False,
        90,
    ),
    (MajorGenre.PLACE_POOL, Category.PLACE, None, "プール", "ぷーる", "", True, 100),
    (
        MajorGenre.PLACE_FITTING_ROOM,
        Category.PLACE,
        None,
        "試着室",
        "しちゃくしつ",
        "",
        False,
        110,
    ),
    (
        MajorGenre.PLACE_PREVIEW_ROOM,
        Category.PLACE,
        None,
        "試写室",
        "ししゃしつ",
        "",
        False,
        120,
    ),
    (
        MajorGenre.PLACE_OUTDOOR,
        Category.PLACE,
        None,
        "野外・露出",
        "やがい ろしゅつ",
        "",
        False,
        130,
    ),
    # =========================
    # シチュエーション
    # =========================
    (
        MajorGenre.SITUATION_RELATION,
        Category.SITUATION,
        None,
        "関係性",
        "かんけいせい",
        "",
        True,
        10,
    ),
    (
        MajorGenre.SITUATION_SCENE,
        Category.SITUATION,
        None,
        "シーン",
        "しーん",
        "",
        True,
        20,
    ),
    (
        MajorGenre.SITUATION_FUZOKU,
        Category.SITUATION,
        None,
        "風俗",
        "ふうぞく",
        "",
        True,
        30,
    ),
    (
        MajorGenre.SITUATION_JOB,
        Category.SITUATION,
        None,
        "職業",
        "しょくぎょう",
        "",
        True,
        40,
    ),
    (
        MajorGenre.SITUATION_NTR,
        Category.SITUATION,
        None,
        "寝取り・寝取られ・NTR",
        "ねとり ねとられ えぬてぃーあーる",
        "",
        True,
        50,
    ),
    # =========================
    # 女優
    # =========================
    (
        MajorGenre.PERSON_STYLE,
        Category.PERSON_F,
        None,
        "スタイル",
        "すたいる",
        "",
        True,
        10,
    ),
    (MajorGenre.PERSON_BREAST, Category.PERSON_F, None, "胸", "むね", "", True, 20),
    (MajorGenre.PERSON_HIP, Category.PERSON_F, None, "お尻", "おしり", "", True, 30),
    (MajorGenre.PERSON_LEG, Category.PERSON_F, None, "脚", "あし", "", True, 40),
    (MajorGenre.PERSON_TYPE, Category.PERSON_F, None, "タイプ", "たいぷ", "", True, 50),
    (
        MajorGenre.PERSON_PERSONALITY,
        Category.PERSON_F,
        None,
        "性格",
        "せいかく",
        "",
        True,
        60,
    ),
    (
        MajorGenre.PERSON_HAIR_STYLE,
        Category.PERSON_F,
        None,
        "髪型",
        "かみがた",
        "",
        True,
        70,
    ),
    (
        MajorGenre.PERSON_HAIR_COLOR,
        Category.PERSON_F,
        None,
        "髪色",
        "かみいろ",
        "",
        True,
        80,
    ),
    (MajorGenre.PERSON_VOICE, Category.PERSON_F, None, "声", "こえ", "", True, 90),
    # =========================
    # 男優
    # =========================
    (
        MajorGenre.PERSON_M_STYLE,
        Category.PERSON_M,
        None,
        "スタイル",
        "すたいる",
        "",
        True,
        10,
    ),
    (
        MajorGenre.PERSON_M_TYPE,
        Category.PERSON_M,
        None,
        "タイプ",
        "たいぷ",
        "",
        True,
        20,
    ),
    # =========================
    # プレイ
    # =========================
    (
        MajorGenre.PLAY_SEIJOUI,
        Category.PLAY,
        None,
        "正常位",
        "せいじょうい",
        "",
        False,
        10,
    ),
    (
        MajorGenre.PLAY_KIJOUI,
        Category.PLAY,
        None,
        "騎乗位",
        "きじょうい",
        "",
        False,
        20,
    ),
    (MajorGenre.PLAY_BACK, Category.PLAY, None, "バック", "ばっく", "", True, 30),
    (
        MajorGenre.PLAY_FELLATIO,
        Category.PLAY,
        None,
        "フェラ",
        "ふぇら",
        "",
        True,
        40,
    ),
    (MajorGenre.PLAY_HANDJOB, Category.PLAY, None, "コキ", "こき", "", True, 50),
    (MajorGenre.PLAY_SQUIRT, Category.PLAY, None, "潮吹き", "しおふき", "", True, 60),
    (
        MajorGenre.PLAY_LOTION,
        Category.PLAY,
        None,
        "ローション・オイル",
        "ろーしょん おいる",
        "",
        True,
        70,
    ),
    (MajorGenre.PLAY_MULTI, Category.PLAY, None, "複数", "ふくすう", "", True, 80),
    (
        MajorGenre.PLAY_MULTI_F1,
        Category.PLAY,
        None,
        "複数（女1）",
        "ふくすう おんないち",
        "",
        True,
        90,
    ),
    (
        MajorGenre.PLAY_MULTI_M1,
        Category.PLAY,
        None,
        "複数（男1）",
        "ふくすう おとこいち",
        "",
        True,
        100,
    ),
    (
        MajorGenre.PLAY_MULTI_MULTI,
        Category.PLAY,
        None,
        "複数（多：多）",
        "ふくすう た た",
        "",
        True,
        110,
    ),
    (
        MajorGenre.PLAY_FINISH,
        Category.PLAY,
        None,
        "フィニッシュ",
        "ふぃにっしゅ",
        "",
        True,
        120,
    ),
    (MajorGenre.PLAY_RAPE, Category.PLAY, None, "レイプ", "れいぷ", "", False, 130),
    (MajorGenre.PLAY_DRUG, Category.PLAY, None, "媚薬", "びやく", "", True, 140),
    (MajorGenre.PLAY_FOREPLAY, Category.PLAY, None, "前戯", "ぜんぎ", "", True, 150),
    (
        MajorGenre.PLAY_DEBUT,
        Category.PLAY,
        None,
        "筆おろし",
        "ふでおろし",
        "",
        False,
        160,
    ),
    (
        MajorGenre.PLAY_HARD,
        Category.PLAY,
        None,
        "淫乱・ハード系",
        "いんらんはーどけい",
        "",
        True,
        170,
    ),
    (MajorGenre.PLAY_TOY, Category.PLAY, None, "おもちゃ", "おもちゃ", "", True, 180),
    (MajorGenre.PLAY_FETISH, Category.PLAY, None, "フェチ", "ふぇち", "", True, 190),
    (
        MajorGenre.PLAY_HAMEDORI,
        Category.PLAY,
        None,
        "ハメ撮り",
        "はめどり",
        "",
        False,
        200,
    ),
    (MajorGenre.PLAY_SWEATY, Category.PLAY, None, "汗だく", "あせだく", "", False, 210),
    (MajorGenre.PLAY_SHUKAN, Category.PLAY, None, "主観", "しゅかん", "", False, 220),
    (
        MajorGenre.PLAY_ONANIE,
        Category.PLAY,
        None,
        "オナニー",
        "おなにー",
        "",
        False,
        230,
    ),
    (
        MajorGenre.PLAY_ITAZURA,
        Category.PLAY,
        None,
        "イタズラ",
        "いたずら",
        "",
        False,
        240,
    ),
    (MajorGenre.PLAY_LES, Category.PLAY, None, "レズ", "れず", "", True, 250),
    (
        MajorGenre.PLAY_SOKUHAME,
        Category.PLAY,
        None,
        "即ハメ",
        "そくはめ",
        "",
        False,
        260,
    ),
    # =========================
    # 作品
    # =========================
    (
        MajorGenre.WORK_FAN_APPRECIATION,
        Category.WORK,
        None,
        "ファン感謝・訪問",
        "ふぁんかんしゃ ほうもん",
        "",
        False,
        10,
    ),
    (
        MajorGenre.WORK_ORIGINAL_COLLAB,
        Category.WORK,
        None,
        "原作コラボ",
        "げんさく こらぼ",
        "",
        False,
        20,
    ),
    (
        MajorGenre.WORK_8K_VR,
        Category.WORK,
        None,
        "8KVR",
        "はちけー ぶいあーる",
        "",
        False,
        30,
    ),
    (MajorGenre.WORK_4K, Category.WORK, None, "4K", "よんけー", "", False, 40),
    (
        MajorGenre.WORK_ACTRESS_BEST,
        Category.WORK,
        None,
        "女優ベスト・総集編",
        "じょゆう べすと そうしゅうへん",
        "",
        False,
        50,
    ),
    (
        MajorGenre.WORK_16H_OVER,
        Category.WORK,
        None,
        "16時間以上作品",
        "じゅうろくじかんいじょう さくひん",
        "",
        False,
        60,
    ),
    (
        MajorGenre.WORK_HIGH_QUALITY_VR,
        Category.WORK,
        None,
        "ハイクオリティVR",
        "はいくおりてぃ ぶいあーる",
        "",
        False,
        70,
    ),
    (
        MajorGenre.WORK_COLLAB,
        Category.WORK,
        None,
        "コラボ作品",
        "こらぼ さくひん",
        "",
        False,
        80,
    ),
    (MajorGenre.WORK_REPRINT, Category.WORK, None, "復刻", "ふっこく", "", False, 90),
    (
        MajorGenre.WORK_4H_OVER,
        Category.WORK,
        None,
        "4時間以上作品",
        "よじかんいじょう さくひん",
        "",
        False,
        100,
    ),
    (
        MajorGenre.WORK_DEBUT,
        Category.WORK,
        None,
        "デビュー作品",
        "でびゅー さくひん",
        "",
        False,
        110,
    ),
    (
        MajorGenre.WORK_BEST,
        Category.WORK,
        None,
        "ベスト・総集編",
        "べすと そうしゅうへん",
        "",
        False,
        120,
    ),
    (
        MajorGenre.WORK_SOLO,
        Category.WORK,
        None,
        "単体作品",
        "たんたい さくひん",
        "",
        False,
        130,
    ),
]

class Command(BaseCommand):
    help = "Seed MajorGenre. Idempotent."

    @transaction.atomic
    def handle(self, *args, **options):
        self.stdout.write(self.style.NOTICE("Seeding major genres..."))
        
        MediumGenre.objects.all().delete()
        MajorGenre.objects.all().delete()

        for (
            id,
            category_id,
            dmm_id,
            name,
            ruby,
            list_url_dmm,
            is_must_medium,
            sort_order,
        ) in MAJOR_SEEDS:
            MajorGenre.objects.update_or_create(
                id=id,
                defaults={
                    "category_id": category_id,
                    "dmm_id": dmm_id,
                    "name": name,
                    "ruby": ruby,
                    "list_url_dmm": list_url_dmm,
                    "is_must_medium": is_must_medium,
                    "sort_order": sort_order,
                    "is_active": True,
                },
            )

        self.stdout.write(self.style.SUCCESS("✅ seed_major_genre completed."))
